server:
  port: 8080
  context-path: /renren

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/renren?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username:  root
    password:  123456
    driver-class-name: com.mysql.cj.jdbc.Driver

